
version: 2

sources:
    - name: staging
      database: dtc-de-375315
      schema: trips_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: external_green_tripdata
        - name: external_yellow_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}
